# Generated by Django 2.0.5 on 2018-10-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_person_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
